const state={quick:'all',category:'all',area:'all',rain:'all',search:'',sort:'default'};
const areaOrder=['馬公市區','湖西','澎南','白沙','西嶼'];
const categoryOrder=['展館','景點','美食','咖啡廳','玩水'];
const places=(window.PLACES||[]).map((p,i)=>({name:p.name||p.n,area:p.area||p.a,categories:p.categories||p.c||[],rainy:p.rainy||p.r,tags:p.tags||p.t||[],note:p.note||p.d,mapQuery:p.mapQuery||p.q,googleRating:p.googleRating??p.gr,googleReviewCount:p.googleReviewCount??p.gc,ratingUpdatedAt:p.ratingUpdatedAt||p.ru||'待從 Google Maps 手動確認',waterType:p.waterType||p.wt||'',familyFriendly:!!(p.familyFriendly||p.wf),needOperator:!!(p.needOperator||p.op),safetyLevel:p.safetyLevel||p.sl||'',order:p.order||i+1}));
const cardsEl=document.querySelector('#cards');
const template=document.querySelector('#cardTemplate');
const resultCountEl=document.querySelector('#resultCount');
const activeFiltersEl=document.querySelector('#activeFilters');
function categoriesText(p){return Array.isArray(p.categories)?p.categories.join('、'):''}
function hasCategory(p,c){return (p.categories||[]).includes(c)}
function rainClass(r){if(r==='可以')return 'rain-ok';if(r==='勉強可以')return 'rain-mid';return 'rain-no'}
function ratingText(p){if(typeof p.googleRating==='number'){const count=typeof p.googleReviewCount==='number'?`${p.googleReviewCount.toLocaleString('zh-TW')} 則`:'評論數待更新';return `⭐ <strong>${p.googleRating.toFixed(1)}</strong>（${count}）<br><span>更新：${p.ratingUpdatedAt}</span>`}return `⭐ <strong>Google 評價：待更新</strong><br><span>${p.ratingUpdatedAt}</span>`}
function mapsDirectionsUrl(p){return `https://www.google.com/maps/dir/?api=1&destination=${encodeURIComponent(p.mapQuery||p.name)}`}
function mapsSearchUrl(p){return `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(p.mapQuery||p.name)}`}
function matchesQuick(p){switch(state.quick){case'all':return true;case'rainy':return p.rainy==='可以';case'highRating':return typeof p.googleRating==='number'&&p.googleRating>=4;case'popular':return typeof p.googleReviewCount==='number'&&p.googleReviewCount>=500;case'superPopular':return typeof p.googleReviewCount==='number'&&p.googleReviewCount>=1000;case'water':return hasCategory(p,'玩水');case'familyWater':return hasCategory(p,'玩水')&&p.familyFriendly;case'needOperator':return p.needOperator;case'ratingPending':return typeof p.googleRating!=='number';default:return true}}
function matchesSearch(p){const q=state.search.trim().toLowerCase();if(!q)return true;const h=[p.name,p.area,categoriesText(p),p.rainy,p.note,p.waterType,p.safetyLevel,...(p.tags||[])].filter(Boolean).join(' ').toLowerCase();return h.includes(q)}
function filteredPlaces(){let list=places.filter(p=>matchesQuick(p)&&(state.category==='all'||hasCategory(p,state.category))&&(state.area==='all'||p.area===state.area)&&(state.rain==='all'||p.rainy===state.rain)&&matchesSearch(p));return [...list].sort((a,b)=>{if(state.sort==='ratingDesc')return (b.googleRating??-1)-(a.googleRating??-1)||a.order-b.order;if(state.sort==='reviewsDesc')return (b.googleReviewCount??-1)-(a.googleReviewCount??-1)||a.order-b.order;if(state.sort==='area')return areaOrder.indexOf(a.area)-areaOrder.indexOf(b.area)||a.order-b.order;if(state.sort==='category'){const ca=a.categories[0],cb=b.categories[0];return categoryOrder.indexOf(ca)-categoryOrder.indexOf(cb)||a.order-b.order}return a.order-b.order})}
function buildFilterLabel(){const labels=[];if(state.quick!=='all')labels.push(document.querySelector(`[data-filter-group="quick"] [data-value="${state.quick}"]`)?.textContent||state.quick);if(state.category!=='all')labels.push(state.category);if(state.area!=='all')labels.push(state.area);if(state.rain!=='all')labels.push(`雨天：${state.rain}`);if(state.search)labels.push(`搜尋：${state.search}`);return labels.length?labels.join(' / '):'全部景點'}
function render(){const list=filteredPlaces();cardsEl.innerHTML='';if(list.length===0){cardsEl.innerHTML='<div class="empty">沒有符合條件的地點。可以放寬篩選，或先點「評價待補」檢查尚未填 Google 評價的點。</div>'}else{const frag=document.createDocumentFragment();list.forEach(p=>{const node=template.content.cloneNode(true);const card=node.querySelector('.card');card.querySelector('h3').textContent=p.name;card.querySelector('.meta').textContent=`${p.area}｜${categoriesText(p)}`;const rb=card.querySelector('.rainBadge');rb.textContent=`雨天：${p.rainy}`;rb.classList.add(rainClass(p.rainy));card.querySelector('.rating').innerHTML=ratingText(p);card.querySelector('.note').textContent=p.note||'';const tagList=card.querySelector('.tagList');(p.tags||[]).slice(0,8).forEach(tag=>{const s=document.createElement('span');s.className='tag';s.textContent=tag;tagList.appendChild(s)});const wi=card.querySelector('.waterInfo');if(hasCategory(p,'玩水')){const bits=[p.waterType,p.safetyLevel].filter(Boolean);wi.textContent=bits.length?`玩水資訊：${bits.join('｜')}`:'玩水資訊：請注意天候與浪況'}else wi.remove();card.querySelector('.mapBtn').href=mapsDirectionsUrl(p);card.querySelector('.searchBtn').href=mapsSearchUrl(p);frag.appendChild(node)});cardsEl.appendChild(frag)}resultCountEl.textContent=`${list.length} 個地點`;activeFiltersEl.textContent=buildFilterLabel()}
document.querySelectorAll('.chips').forEach(group=>{group.addEventListener('click',e=>{const btn=e.target.closest('.chip');if(!btn)return;const groupName=group.dataset.filterGroup;group.querySelectorAll('.chip').forEach(el=>el.classList.remove('is-active'));btn.classList.add('is-active');state[groupName]=btn.dataset.value;render()})});
document.querySelector('#searchInput').addEventListener('input',e=>{state.search=e.target.value;render()});
document.querySelector('#sortSelect').addEventListener('change',e=>{state.sort=e.target.value;render()});
render();
